learned def
RYO515/test pull request #2
Opened 2021-01-16 11:12 UTC by RYO515

Pythonふりがなの本買って勉強中

2021-01-16 14:31 UTC, tetsu5555 commented
なんか`furigana/chapter4/__pycache__/chap4func.cpython-38.pyc`みたいなの間違って入ってない？
あと、同じ内容のファイルが複数あるかも

2021-01-16 14:39 UTC, tetsu5555 commented
あと、commitはもうちょい小さい単位の方がいいかも

2021-01-16 14:46 UTC, RYO515 commented
おれもfurigana/chapter4/__pycache__/chap4func.cpython-38.pycのファイルを作った覚えがないんだけどpythonでimportする時にそれ用のファイルが必要って動画で見たから消さずにそのまま残してる

2021-01-16 23:01 UTC, tetsu5555 commented on furigana/chapter4/chap4-6.py
> +    chap4func.create_mail(rec['name'],bill)
ファイルの最後に改行入れるようにしてほしい
入れないとこの赤いマーク出るから

2021-01-16 23:03 UTC, tetsu5555 commented
gitignore設定しよう

https://techacademy.jp/magazine/10179

2021-01-16 23:03 UTC, tetsu5555 requested changes
変更よろしく！

2021-01-17 01:47 UTC, tetsu5555 commented
あとパッケージの管理はrequirements.txtを使った方がいい

https://note.nkmk.me/python-pip-install-requirements/

2021-01-17 02:19 UTC, merged